version: "3.1"
services:

    postgres:
      image: postgres:latest
      container_name: db
      working_dir: /application
      volumes:
        - ./phpdocker/db:/application
      environment:
        - POSTGRES_USER=
        - POSTGRES_PASSWORD=
        - POSTGRES_DB=
      ports:
        - "8084:5432"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

